name: Download and Send Logs to Splunk

on:
  workflow_run:
    workflows: ["Terraform Manual Deploy"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  download-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq unzip curl

      - name: Download logs
        run: |
          echo "🔧 Downloading logs from GitHub API..."
          curl -sL \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -o logs.zip \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/logs"

          echo "📦 Inspecting logs..."
          file logs.zip || echo "File type check failed"
          unzip -o logs.zip -d logs_folder || echo "Failed to unzip"

          for logfile in $(find logs_folder -type f -name "*.txt"); do
            LOG_CONTENT=$(jq -Rs . < "$logfile")
            PAYLOAD=$(jq -n \
              --arg log "$LOG_CONTENT" \
              --arg filename "$logfile" \
              --arg run_id "${{ github.event.workflow_run.id }}" \
              --arg workflow "${{ github.event.workflow_run.name }}" \
              '{
                event: {
                  run_id: $run_id,
                  workflow: $workflow,
                  file: $filename,
                  content: $log
                },
                sourcetype: "github-logs",
                index: "main"
              }')

            curl -s -k -X POST \
              -H "Authorization: Splunk $HEC_TOKEN" \
              -H "Content-Type: application/json" \
              -d "$PAYLOAD" \
              "$HEC_URL/services/collector/event"
          done
        env:
          HEC_TOKEN: ${{ secrets.SPLUNK_HEC_TOKEN }}
          HEC_URL: ${{ secrets.SPLUNK_HEC_URL }}
